FROM php:7.1.3-fpm-alpine

ENV BUILD_DEPS \
        build-base \
        bash \
        less \
        vim \
        curl-dev \
        icu \
        icu-dev \
        libxml2 \
        libxml2-dev \
        libmemcached-dev \
        pcre-dev

ENV PHP_EXTENSIONS \
        curl \
        intl \
        mbstring \
        xml \
        json \
        simplexml \
        ctype \
        opcache \
        tokenizer \
        zip

RUN apk update \
    && apk add --no-cache \
        $BUILD_DEPS \
    && docker-php-ext-install \
        $PHP_EXTENSIONS \
    && rm -rf /tmp/* /var/tmp/*


# configure your php environment
COPY ./dockerfiles/zz-docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf
COPY ./dockerfiles/php.ini /usr/local/etc/php/php.ini

RUN mkdir /var/www/public/
RUN echo "<?php echo 'OK';" > /var/www/public/index.php

# create log dir
RUN mkdir -p /var/log/php/
RUN chown www-data:www-data -R /var/log

WORKDIR /var/www

EXPOSE 9000
CMD ["php-fpm"]